### ISSUE TITLE
Spotify keeps crashing, not sure why

### ISSUE THREAD

**Issue by Adept9559** [hassio-addons/addon-spotify-connect#274]
# Problem/Motivation

> Spotify Connect keeps crashing. Does not restart correctly.

## Expected behavior

> Stay connected to begin with. Or restart correctly upon crash

## Actual behavior

> Crashes and loops

## Steps to reproduce

> not sure

## Proposed changes

> Not sure

Log:    -I removed my username
[2024-10-30T01:03:29Z INFO  librespot_playback::player] <Jungle> (198805 ms) loaded
[2024-10-30T03:53:16Z ERROR librespot_core::session] Connection reset by peer (os error 104)
[2024-10-30T03:53:16Z ERROR librespot_connect::spirc] subscription terminated
[2024-10-30T03:53:16Z WARN  librespot] Spirc shut down unexpectedly
[2024-10-30T03:53:16Z WARN  librespot_core::apresolve] Ignoring blacklisted access point ap-gew4.spotify.com:80
[2024-10-30T03:53:16Z INFO  librespot_core::session] Connecting to AP "ap-guc3.spotify.com:4070"
[2024-10-30T03:53:16Z INFO  librespot_core::session] Authenticated as "" !
[2024-10-30T03:53:16Z INFO  librespot_playback::mixer::softmixer] Mixing with softvol and volume control: Log(60.0)
[2024-10-30T03:53:16Z INFO  librespot_core::session] Country: "CA"
[2024-10-30T03:53:16Z INFO  librespot_playback::convert] Converting with ditherer: tpdf
[2024-10-30T03:53:16Z INFO  librespot_playback::audio_backend::pulseaudio] Using PulseAudioSink with format: S16
[2024-10-30T04:01:17Z ERROR librespot_core::session] Connection reset by peer (os error 104)
[2024-10-30T04:01:17Z ERROR librespot_connect::spirc] subscription terminated
[2024-10-30T04:01:17Z WARN  librespot] Spirc shut down unexpectedly
[2024-10-30T04:01:17Z WARN  librespot_core::apresolve] Ignoring blacklisted access point ap-gue1.spotify.com:4070
[2024-10-30T04:01:17Z WARN  librespot_core::apresolve] Ignoring blacklisted access point ap-gew4.spotify.com:80
[2024-10-30T04:01:17Z INFO  librespot_core::session] Connecting to AP "ap-guc3.spotify.com:4070"
[2024-10-30T04:01:17Z INFO  librespot_core::session] Authenticated as "" !
[2024-10-30T04:01:17Z INFO  librespot_playback::mixer::softmixer] Mixing with softvol and volume control: Log(60.0)
[2024-10-30T04:01:17Z INFO  librespot_playback::convert] Converting with ditherer: tpdf
[2024-10-30T04:01:17Z INFO  librespot_playback::audio_backend::pulseaudio] Using PulseAudioSink with format: S16
[2024-10-30T04:01:17Z INFO  librespot_core::session] Country: "CA"
[2024-10-30T04:45:17Z ERROR librespot_core::session] Connection reset by peer (os error 104)
[2024-10-30T04:45:17Z ERROR librespot_connect::spirc] subscription terminated
[2024-10-30T04:45:17Z WARN  librespot] Spirc shut down unexpectedly
[2024-10-30T04:45:17Z WARN  librespot_core::apresolve] Ignoring blacklisted access point ap-gue1.spotify.com:443
[2024-10-30T04:45:17Z WARN  librespot_core::apresolve] Ignoring blacklisted access point ap-gew4.spotify.com:80
[2024-10-30T04:45:17Z INFO  librespot_core::session] Connecting to AP "ap-guc3.spotify.com:4070"
[2024-10-30T04:45:18Z INFO  librespot_core::session] Authenticated as "" !
[2024-10-30T04:45:18Z INFO  librespot_playback::mixer::softmixer] Mixing with softvol and volume control: Log(60.0)
[2024-10-30T04:45:18Z INFO  librespot_playback::convert] Converting with ditherer: tpdf
[2024-10-30T04:45:18Z INFO  librespot_playback::audio_backend::pulseaudio] Using PulseAudioSink with format: S16
[2024-10-30T04:45:18Z INFO  librespot_core::session] Country: "CA"
[2024-10-30T11:13:20Z ERROR librespot_core::session] Connection reset by peer (os error 104)
[2024-10-30T11:13:20Z ERROR librespot_connect::spirc] subscription terminated
[2024-10-30T11:13:20Z WARN  librespot] Spirc shut down unexpectedly
[2024-10-30T11:13:20Z WARN  librespot_core::apresolve] Ignoring blacklisted access point ap-gue1.spotify.com:443
[2024-10-30T11:13:20Z WARN  librespot_core::apresolve] Ignoring blacklisted access point ap-gew4.spotify.com:80
[2024-10-30T11:13:20Z INFO  librespot_core::session] Connecting to AP "ap-guc3.spotify.com:4070"
[2024-10-30T11:13:21Z INFO  librespot_core::session] Authenticated as "" !
[2024-10-30T11:13:21Z INFO  librespot_playback::mixer::softmixer] Mixing with softvol and volume control: Log(60.0)
[2024-10-30T11:13:21Z INFO  librespot_playback::convert] Converting with ditherer: tpdf
[2024-10-30T11:13:21Z INFO  librespot_playback::audio_backend::pulseaudio] Using PulseAudioSink with format: S16
[2024-10-30T11:13:21Z INFO  librespot_core::session] Country: "CA"
[2024-10-30T11:25:21Z ERROR librespot_core::session] Connection reset by peer (os error 104)
[2024-10-30T11:25:21Z ERROR librespot_connect::spirc] subscription terminated
[2024-10-30T11:25:21Z WARN  librespot] Spirc shut down unexpectedly
[2024-10-30T11:25:21Z WARN  librespot_core::apresolve] Ignoring blacklisted access point ap-gue1.spotify.com:4070
[2024-10-30T11:25:21Z WARN  librespot_core::apresolve] Ignoring blacklisted access point ap-gew4.spotify.com:80
[2024-10-30T11:25:21Z INFO  librespot_core::session] Connecting to AP "ap-guc3.spotify.com:4070"
[2024-10-30T11:25:21Z ERROR librespot] Connection failed: Cannot create session: Connection refused (os error 111)
[04:25:21] WARNING: spotifyd crashed, halting add-on
[04:25:21] INFO: spotifyd stoped, restarting...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

**Comment by spoetnik** [comment]
Can confirm! Unusable at the moment
![IMG_5549](https://github.com/user-attachments/assets/c587fb7c-7530-442d-8db6-fe7b8dd9075e)

**Comment by spoetnik** [comment]
For me its unusable because the volume get reset to level "Mayhem' after the crash. I can't find a way to configure the default volume

**Comment by joryvd** [comment]
Was just about to propose this, or look into it! +1 for this PR

**Comment by dayofdoom** [comment]
Running into this issue too! Grateful for the software, it's very nice. Been trying to troubleshoot the disconnecting multiple times a day and the loud volume reconnects. Thought it was isolated to my install.

**Comment by nedguy** [comment]
I'm running into this as well, it looks like something that has been addressed in librespot v0.5.0 [PR#1359](https://github.com/librespot-org/librespot/pull/1359).  I saw that there was a recent PR to integrate librespot v0.6.0.  Is there a way to deploy prerelease builds to Home Assistant to see if the issue is addressed or is a full release needed?

**Comment by joryvd** [comment]
@nedguy perhaps what you can do is fork the repo and then add it to home assistant manually

**Comment by joryvd** [comment]
Still have this issue from time to time where it just drops out and I have to reconnect via Spotify. Haven't had the chance to test this branch on my system yet, will put it on my to-do

**Comment by frenck** [comment]
Please try https://github.com/hassio-addons/addon-spotify-connect/releases/tag/v0.14.0

**Comment by InuSasha** [comment]
Update yesterday, afternoon
Today: no single crash the wohle day 👍

**Comment by dayofdoom** [comment]
Thanks to frenck for updating, I can confirm there are less issues with dropout of audio, went a few days without a single drop. Had one happen this morning - unsure if it was integration issue or Spotify issue.

**Comment by frenck** [comment]
Allright, I'm going to close out this issue for now in that case 👍 

Thanks for getting back!

../Frenck
